### ISSUE TITLE
Initial flashing of index route on page load (when another route is requested)

### ISSUE THREAD

**Issue by kemalcany** [antfu/vitesse#159]
Hi!

When you open the app with a different route than index (as its seen in /about below), there is a split second of index route flashing. Happens both on static and dynamic routes.

You can observe this behaviour (although it's very quick) on the official example behaviour as well:

https://vitesse.netlify.app/about
or
https://vitesse.netlify.app/hi/something

Is this the expected behaviour? Is there a way to avoid this, even if that means a slower initial page load?

Thank you!

**Comment by antfu** [comment]
SSG seem to broken, investigating.

**Comment by antfu** [comment]
Looks like it's mainly because PWA is serving the wrong file, /cc @userquin do you have any idea on how could we make PWA aware of the url prettify?

**Comment by userquin** [comment]
@antfu The problem is that routes are not included in the sw manifest, and so the router will get the `index.html` response, and then redirected from router logic: the flash occurs while resolving requested page assets (router page transition from index to requested).

If you look at the `sw.js` file from netlify you can see `home`, `404` and `about` routes are missing from the precache and so the problem isn't from url prettify, first we need to include them on sw precache and then make them url pretiffy aware.

I'm looking for a way to map routers to logical names and include them into the sw manifest: but I think it will be hard.

In my projects I include them manually.

**Comment by userquin** [comment]
@antfu I have it working, we need to do some changes to track routes using `extendRoute` from `vite-plugin-pages`, you can see it on my branch [here](https://github.com/userquin/vitesse/tree/chore/fix-missing-routes-on-sw).

The changes are on `vite.config.ts` file on `vite-plugin-pages` plugin adding the corresponding `workbox ManifestEntry`.

The problem is that each time the project is built the sw is updated: since the sw is generated on client generation from `vite-ssg` we need to include `extendRoute` on `vite-plugin-pages` to collect all routes, excluding `/ ` and dynamic routes, but we need to calculate the revision entry for `additionalManifestEntries workbox` option, but the corresponding `html` is generated after client generation and so we haven't it, we cannot use the generate `html` to calculate the revision, we only can do some random and use it hash as a revision.

![imagen](https://user-images.githubusercontent.com/6311119/127215272-8b22c58c-637e-4a57-897c-6f53de2c5032.png)

![imagen](https://user-images.githubusercontent.com/6311119/127215160-6fb51c9c-0fbc-4a3e-a1cf-880fd212d179.png)

![imagen](https://user-images.githubusercontent.com/6311119/127215223-531cf88f-529e-4887-9e45-2288753d7b39.png)

![imagen](https://user-images.githubusercontent.com/6311119/127215312-1d8db5c2-8a1d-4101-848e-013c7c188a31.png)

**Comment by userquin** [comment]
@antfu maybe we can change the order on `vite-ssg`, generating client last, collecting routes and once generated then we can calculate the real revision (if the html is not changed, then the sw will not change if none of assets nor routes change). The problem is still on user land, since we need to calculate the revision.

I don't know if we can access to vite configuration and then change the PWA plugin configuration from `vite-ssg` (we'll need to detect it). The real problem is that the mapping is done by `vite-ssg` but the routes comes from `vite-plugin-pages` and we need both, the url for each route and its html on `dist` folder.

**Comment by antfu** [comment]
@userquin thanks for the detailed explanation. Let me take some time to think about how to have them work together properly.

**Comment by userquin** [comment]
@antfu we cannot move client generation to last step since we need the ssr manifest: it is also generated on client build step.

**Comment by userquin** [comment]
@antfu I have an entry on vite about handling `modulepreload` [here](https://github.com/vitejs/vite/discussions/4130), it is also related to this problem. 

I also mention this problem on i18n router discussion entry on vite-ssg, since we have a spa we need to generate also client manifest to extract non index page dependencies to be injected on generated html page.

For dynamic page entries I think we need to find a way on client side to make page transition smooth while resolving inicial router transition.

**Comment by userquin** [comment]
The link for vite-ssg `modulepreload` can be found [here](https://github.com/antfu/vite-ssg/discussions/58#discussioncomment-960863).

**Comment by antfu** [comment]
Fixed with 3112490 by upgrading:

- `vite-plugin-pwa@^0.9.3`
- `vite-ssg@^0.13.0`

Thanks again @userquin for the detailed explanation and working example, even though the approach is a bit different, your solution is definitely helpful :)

**Comment by kemalcany** [comment]
@antfu @userquin  Thank you very much!!!

**Comment by kemalcany** [comment]
Hi!

Looks like this issue is back. Please observe the initial load for this page:

https://vitesse.netlify.app/hi/something

You will see the index page flashing for a split second

**Comment by userquin** [comment]
It is not back, this page is dynamic and so excluded by default from ssg, I wrote about it on discussions a few months ago.

I am checking how to solve this problem.
